apiVersion: kubedb.com/v1alpha1
kind: Postgres
metadata:
  name: postgres-quickstart
  namespace: demo
spec:
  version: "10.2-v2"
  storageType: Durable
  storage:
    storageClassName: "hostpath"
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
#  terminationPolicy: DoNotTerminate
