# https://kubedb.com/docs/0.12.0/guides/mongodb/clustering/sharding/
apiVersion: kubedb.com/v1alpha1
kind: MongoDB
metadata:
  name: mongodb-cluster
  namespace: demo
spec:
  version: 3.6-v3
  shardTopology:
    configServer:
      replicas: 3
      storage:
        resources:
          requests:
            storage: 1Gi
        storageClassName: "hostpath"
    mongos:
      replicas: 2
      strategy:
        type: RollingUpdate
    shard:
      replicas: 3
      shards: 3
      storage:
        resources:
          requests:
            storage: 1Gi
        storageClassName: "hostpath"
