apiVersion: kubedb.com/v1alpha1
kind: MongoDB
metadata:
  name: mongodb-quickstart
  namespace: demo
spec:
  version: "3.4-v3"
  storageType: Durable
  storage:
    storageClassName: "hostpath"
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
#  terminationPolicy: DoNotTerminate
